#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=10
USE_PROCD=1

start_service() {
         procd_open_instance runner
         procd_set_param command /usr/bin/runner -c /etc/config/runner.ini  -b 192.168.2.1:1888 # service executable that has to run in **foreground**.
         # respawn automatically if something died, be careful if you have an alternative process supervisor
         # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
         procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
         procd_set_param limits core="unlimited"  # If you need to set ulimit for your process
         procd_set_param file /etc/config/runner.ini # /etc/init.d/your_service reload will restart the daemon if these files have changed
         procd_set_param stdout 1 # forward stdout of the command to logd
         procd_set_param stderr 1 # same for stderr
         procd_set_param user root # run service as user nobody
         procd_set_param pidfile /var/run/runner.pid # write a pid file on instance start and remove it on stop
         procd_close_instance
}